### ISSUE TITLE
게임 전용 라이브러리 도입 평가(PixiJS, Phaser 등)

### ISSUE THREAD

**Issue by seungineer** [HandTris/FE-HandTris#11]
# 테트리스 화면을 구성해보며 적용 가능성 판단
- 테트리스 게임성 확인
- 애니메이션 적용 가능성 확인

**Comment by bishoe01** [comment]
1. 기존 코드베이스의 유지 보수 및 개선이 더 효율적
2. Phaser를 새로 학습하기엔 부족한 개발기간
3. Tetris 게임의 간단한 특성상높은 프레임이 요구되지 않음
4. 프로젝트 마감 기한을 준수하기 위해 안정적인 현재 구현을 유지함.
5. 줄 클리어 애니메이션이나 공격과 같은 인터렉티브 요소는 웹으로도 충분히 구현 가능
Tetris - Phaser 마이그레이션 이슈를 닫습니다.
