### ISSUE TITLE
핸드조이스틱을 위한 tetris game 화면 UI/UX Version Up

### ISSUE THREAD

**Issue by seungineer** [HandTris/FE-HandTris#37]
## AS-IS
- Glassmorphism 디자인 적용
- Tetris game 배경이 밝고, 블럭도 밝은 디자인
- BGM에 Effect Sound가 적절하게 들리지 않음
## TO-BE
- [x] 핸드조이스틱에 어울리는 옛날 테트리스 배경으로 이미지 변경
- [x] Tetris game 배경을 어두운 색으로, 블럭을 밝은 색으로 디자인 변경
- [x] 플레이어와 상호작용 가능토록 sound 및 effect 적용

**Comment by bishoe01** [comment]
close #41  #42  #43
